spring.application.name=auth-server
server.port=9000

# ========================================
# Authorization Server
# ========================================
spring.security.oauth2.authorizationserver.issuer=${AUTH_SERVER_ISSUER:http://localhost:9000}

# ========================================
# Logging
# ========================================
logging.level.root=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.oauth2=INFO

# ========================================
# Actuator
# ========================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always