spring.application.name=backend-core
server.port=8081

# ========================================
# MySQL
# ========================================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/banco_xyz?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:banco_user}
spring.datasource.password=${DB_PASSWORD:banco_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================================
# JPA / Hibernate
# ========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.orm.jdbc.extract=OFF
spring.jpa.properties.hibernate.format_sql=true

# ========================================
# Eureka
# ========================================
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# ========================================
# Kafka
# ========================================
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}